---

- name: remove autorelabel
  file:
    path: /.autorelabel
    state: absent
    
- name: remove old kernels
  shell: "dnf remove -y $(dnf repoquery --installonly --latest-limit=-2 -q)"
  args:
    warn: no
  changed_when: false

- include_tasks: user.yml

# - include_tasks: ec2.yml
#   when: provider == "ec2"

- include_tasks: packet.yml
  when: provider == "packet"

- include_tasks: linode.yml
  when: provider == "linode"

- include_tasks: yandex.yml
  when: provider == "yandex"

- include_tasks: vagrant.yml
  when: provider == "vagrant"

- meta: flush_handlers
