---

- name: remove autorelabel
  file:
    path: /.autorelabel
    state: absent

- name: remove /etc/motd.d/cockpit
  file:
    path: /etc/motd.d/cockpit
    state: absent

- name: add /usr/local/bin to path
  ansible.builtin.copy:
    src: files/usr-local-bin.sh
    dest: /etc/profile.d/usr-local-bin.sh
    owner: root
    group: root
    mode: '0644'

- name: remove old kernels
  shell: "dnf remove -y $(dnf repoquery --installonly --latest-limit=-2 -q)"
  args:
    warn: false
  changed_when: false

- include_tasks: user.yml

# - include_tasks: ec2.yml
#   when: provider is defined and provider == "ec2"

- include_tasks: metal.yml
  when: provider is defined and provider == "metal"

- include_tasks: linode.yml
  when: provider is defined and provider == "linode"

- include_tasks: yandex.yml
  when: provider is defined and provider == "yandex"

- include_tasks: vagrant.yml
  when: provider is defined and provider == "vagrant"

- name: flush handlers
  meta: flush_handlers
