---

- name: add group
  group: name={{ normalize_username }} state=present

- name: add user without password
  user: name={{ normalize_username }} group={{ normalize_username }}
  when: normalize_password is not defined

- name: add user with password
  user:
    name={{ normalize_username }}
    group={{ normalize_username }}
    password={{ normalize_password | password_hash('sha512') }}
  when: normalize_password is defined

- name: set authorized key
  ansible.posix.authorized_key:
    user: "{{ normalize_username }}"
    state: present
    key: "{{ normalize_key }}"
  when: not((normalize_key is undefined) or (normalize_key is none) or (normalize_key | trim | length == 0))

- name: check groups
  shell: |
    set -o pipefail
    /usr/bin/getent group | awk -F":" '{print $1}'
  args:
    executable: /bin/bash
  register: normalize_groups
  changed_when: false

- name: add secondary groups
  user: name={{ normalize_username }} groups={{ item }} append=true
  when: item in normalize_groups.stdout_lines
  with_items:
    - sudo
    - wheel

- name: Allow {{ normalize_username }} to have passwordless sudo
  lineinfile:
    create: true
    dest: "/etc/sudoers.d/{{ normalize_username }}"
    state: present
    regexp: '^{{ normalize_username }}'
    line: '{{ normalize_username }} ALL=(ALL) NOPASSWD: ALL'
    mode: 0640
