---

- name: add group
  group: name={{ normalize_username }} state=present

- name: add user
  user: name={{ normalize_username }} group={{ normalize_username }}

- name: check groups
  shell: |
    set -o pipefail
    /usr/bin/getent group | awk -F":" '{print $1}'
  args:
    executable: /bin/bash
    warn: false
  register: normalize_groups
  changed_when: false

- name: add secondary groups
  user: name={{ normalize_username }} groups={{ item }} append=true
  when: item in normalize_groups.stdout_lines
  with_items:
    - sudo
    - wheel

- name: Allow {{ normalize_username }} to have passwordless sudo
  lineinfile:
    create: true
    dest: "/etc/sudoers.d/{{ normalize_username }}"
    state: present
    regexp: '^{{ normalize_username }}'
    line: '{{ normalize_username }} ALL=(ALL) NOPASSWD: ALL'
    mode: 0640
