---

- name: fix slow dns
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present

- name: configure ssh daemon
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

- name: configure vagrant .ssh directory
  ansible.builtin.file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: get vagrant's public key
  ansible.builtin.get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

- name: check if virtualbox is running the guest vm
  ansible.builtin.stat:
    path: /home/vagrant/.vbox_version
  register: normalize_virtualbox_check

- ansible.builtin.include_tasks: virtualbox.yml
  when: normalize_virtualbox_check.stat.exists

- name: check if vmware is running the guest vm
  ansible.builtin.shell: |
    set -o pipefail
    cat /proc/scsi/scsi | grep VMware
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: normalize_vmware_check

- ansible.builtin.include_tasks: vmware.yml
  when: normalize_vmware_check.rc == 0

- name: remove redhat interface persistence
  ansible.builtin.command: >
    rm -f /etc/udev/rules.d/70-persistent-net.rules
