---

- name: get the current kernel release
  command: uname -r
  changed_when: false
  register: normalize_kernel_release

- name: ensure necessary packages are installed.
  yum:
    name:
      - "kernel-devel-{{ normalize_kernel_release.stdout }}"
      - python3-libselinux
      - binutils
      - bzip2
      - cifs-utils
      - cpp
      - dkms
      - elfutils-libelf-devel
      - gcc
      - glibc-devel
      - glibc-headers
      - kernel-devel
      - kernel-headers
      - libgomp
      - make
      - patch
      - perl
      - tar
      - wget
    state: present

- name: mount virtualbox guest additions iso
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: run virtualbox guest additions installation
  command: sh /tmp/vbox/VBoxLinuxAdditions.run
  changed_when: true

- name: unmount virtualbox guest additions iso
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions.iso"
    state: absent
    fstype: iso9660

- name: delete virtualbox guest additions iso
  file:
    path: "/home/vagrant/VBoxGuestAdditions.iso"
    state: absent

- name: remove any remnants of virtualbox isos
  shell: >
    rm -rf VBoxGuestAdditions.iso VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?
    warn=false
  args:
    chdir: "/home/vagrant"

- name: remove unneeded packages
  dnf:
    name:
      - cpp
      - kernel-devel
      - kernel-headers
    state: absent
