---

- name: mount virtualbox guest additions iso
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: run virtualbox guest additions installation
  command: sh /tmp/vbox/VBoxLinuxAdditions.run
  changed_when: true

- name: unmount virtualbox guest additions iso
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions.iso"
    state: absent
    fstype: iso9660

- name: delete virtualbox guest additions iso
  file:
    path: "/home/vagrant/VBoxGuestAdditions.iso"
    state: absent

- name: remove any remnants of virtualbox isos
  shell: >
    rm -rf VBoxGuestAdditions.iso VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?
    warn=false
  args:
    chdir: "/home/vagrant"
  tags: ['skip_ansible_lint']
