---
- name: install open-vm-tools
  ansible.builtin.dnf:
    name: open-vm-tools
    state: present

- name: enable vmtoolsd service
  ansible.builtin.service:
    name: vmtoolsd.service
    enabled: true
